sudo: required
services:
  - docker
script:
  - "docker build -t vibioh/wordpress --rm ."
  - "docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}"
  - "docker push vibioh/wordpress"
notifications:
  email: false
