wordpress:
  image: vibioh/wordpress:latest
  read_only: true
mysql:
  image: vibioh/mysql:latest
  read_only: true
  environment:
    - MYSQL_ROOT_PASSWORD=s3cr3t!
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=W0RDPR3SS!
  volumes_from:
    - wordpress
nginx:
  image: vibioh/php:latest
  read_only: true
  volumes_from:
    - wordpress
  links:
    - mysql
  ports:
    - "7000:1080"
