wordpress:
  image: vibioh/wordpress-arm
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.sidekicks: 'mysql, php'
    traefik.enable: 'false'
  restart: 'no'
  read_only: true
  cpu_shares: 128
  mem_limit: 67108864
mysql:
  image: vibioh/mysql-arm
  labels:
    traefik.enable: 'false'
  environment:
    MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    MYSQL_DATABASE: 'wordpress'
    MYSQL_USER: 'wordpress'
    MYSQL_PASSWORD: '${WORDPRESS_PASSWORD}'
  volumes_from:
  - wordpress
  log_opt:
    max-size: '50m'
  restart: 'no'
  read_only: true
  cpu_shares: 512
  mem_limit: 268435456
php:
  image: vibioh/php-arm
  labels:
    traefik.frontend.passHostHeader: 'true'
    traefik.frontend.rule: 'Host: ${WORDPRESS_NAME}.${DOMAIN}'
    traefik.port: '1080'
  environment:
    SMTP_URL: 'smtp'
    SMTP_PORT: '1025'
  links:
  - mysql:db
  volumes_from:
  - wordpress
  log_opt:
    max-size: '50m'
  restart: 'no'
  cpu_shares: 512
  mem_limit: 268435456
